name: Deploy argocd
on:
    workflow_call:
      secrets:
        aws-access-key-id:
           required: true
        aws-secret-access-key:
           required: true
      inputs: 
        aws-region:
           type: string
           required: true
jobs:
     Deploy_argocd:
        name: Deploy argocd
        runs-on: ubuntu-latest

        steps:

          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Set up aws credentials
            uses: aws-actions/configure-aws-credentials@v3
            with:
              aws-access-key-id: ${{ secrets.aws-access-key-id }}
              aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
              aws-region: ${{ inputs.aws-region }}

          - name: Update kube config
            run: |
                 aws eks update-kubeconfig --name ${{ vars.CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}
                 
          - name: Deploy argocd
            run: |
                 kubectl create namespace argocd
                 kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

