name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  tf_fmt:
    name: Setting up Terraform
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan  
      run: terraform plan -lock=false
    
    - name: Terraform Apply
      run: terraform apply -auto-approve
