name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  tf_fmt:
    name: Setting up Terraform
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Export TF_VARS
      run: |
        export TF_VAR_AWS_REGION="${{ vars.AWS_REGION }}"
        echo TF_VAR_AWS_REGION

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: Terraform init
      run: terraform init

    - name: Terraform prepare
      run: terraform validate
      
    #- name: terraform destroy
    #  run: terraform destroy -lock=false -auto-approve

    - name: Terraform plan
      run: terraform plan -lock=false -out=tfplan

    - name: Terraform apply
      run: terraform apply -lock=false -auto-approve tfplan