name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  tf_fmt:
    name: Setting up Terraform
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Export TF vars
      run : |
        export TF_VAR_aws_access_key="${{ secrets.AWS_ACCESS_KEY }}"
        export TF_VAR_aws_secret_key="${{ secrets.AWS_SECRET_KEY }}"
    
    - name: terraform init
      run: |
        terraform init \
        -backend-config="access_key=${TF_VAR_aws_access_key}" \
        -backend-config="secret_key=${TF_VAR_aws_secret_key}" \
        -backend-config="region=${{ vars.AWS_REGION }}" \
        

    - name: Terraform plan
      run: |
        terraform plan -lock=false 
    
