name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  tf_fmt:
    name: Setting up Terraform
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    - name: terraform init
      run: |
        terraform init \
        -backend-config="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
        -backend-config="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
        -backend-config="region=${{ vars.AWS_REGION }}" \
        

    - name: Terraform plan
      run: |
        terraform plan -lock=false 
    
