name: Deploy Infrastructure

on:
  workflow_dispatch:

jobs:
  tf_fmt:
    name: Setting up Terraform
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
    
    
    - name: Create Secret file
      env:
        SECRETS: '${{ toJson(secrets) }}'
      run: |
        for secret in $(echo "$SECRETS" | jq -r 'keys[]'); do
            value="$(jq -r --arg key "$secret" '.[$key]' <<< "$SECRETS")"
            echo "$secret=$value" >> secrets.auto.tfvars
        done

    - name: Append Github Vars to ConfigMap
      env:
        VARS: '${{ toJson(vars) }}'
      run: |
        for vars in $(echo "$VARS" | jq -r 'keys[]'); do
            value="$(jq -r --arg key "$vars" '.[$key]' <<< "$VARS")"
            echo -e "\n$vars=$value" >> secrets.auto.tfvars
        done

      
    - name: terraform init
      run: terraform init

    - name: terraform plan
      run: terraform plan